name: arachnoit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_cropper: ^1.3.1
  image_picker: ^0.7.4
  file_picker: ^3.0.1
  flutter_downloader: ^1.5.2

  auto_direction: ^0.0.4+1
  better_player: ^0.0.55
  cached_network_image: ^2.5.0
  clippy_flutter: ^1.1.1
  cupertino_icons: ^1.0.0
  device_info: ^2.0.0
  dio: ^4.0.0
  flutter_swiper: ^1.1.6
  equatable: ^2.0.0
  expand_widget: ^1.2.0+1
  extended_nested_scroll_view: ^3.0.1
  flutter_bloc: ^7.0.0
  flutter_html: 2.0.0-nullsafety.1
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  formz: ^0.3.2
  get_it: ^5.0.1
  intl: ^0.17.0
  inview_notifier_list: ^1.0.0
  local_auth: ^1.1.5
  material_floating_search_bar: ^0.2.6
  path_provider: ^2.0.1
  permission_handler: ^8.0.0+2
  photo_view: ^0.10.3
  pinput: ^1.0.0
  pretty_dio_logger: ^1.1.1
  progress_dialog: ^1.2.4
  rxdart: ^0.24.0
  shared_preferences: ^2.0.6
  uni_links: ^0.4.0
  url_launcher: ^6.0.3
  sliding_sheet: ^0.4.1
  wifi_info_flutter: ^2.0.0
  material_design_icons_flutter: ^4.0.5955
  popup_menu: ^1.0.5
  share: ^2.0.1
  flutter_link_previewer: ^2.0.1
  video_thumbnail: ^0.3.3
  # flutter_mapbox_navigation: ^0.0.24
  flutter_search_bar: ^2.1.0
  pull_to_refresh: ^2.0.0
  flutter_statusbarcolor: ^0.2.3
  flutter_image_compress: ^1.0.0
  flutter_facebook_auth: ^3.4.1
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
  flutter_local_notifications: ^6.0.0
  http: ^0.13.3
  google_sign_in: ^5.0.4
  firebase_auth: ^2.0.0
  horizontal_blocked_scroll_physics: ^4.0.0
  open_store: ^0.2.4
  connectivity_plus: ^1.0.6
  data_connection_checker: ^0.3.4
  package_info: ^2.0.2
  sign_in_with_apple: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/circular/Circular-Std-Bold.ttf
          weight: 700
        - asset: assets/fonts/circular/Circular-Std-Book.ttf
        - asset: assets/fonts/circular/Circular-Std-Medium.ttf
        - asset: assets/fonts/circular/Circular-Std-Bold-Italic.ttf
          style: italic
    - family: Northwell
      fonts:
        - asset: assets/fonts/northwell/Northwell-Alt.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.otf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.otf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.otf
        - asset: assets/fonts/montserrat/Montserrat-Thin.otf
    - family: Reey
      fonts:
        - asset: assets/fonts/reey/reey-regular.otf
          weight: 400
